site_name: Apunts de Stop Motion
site_description: Recursos de classe sobre animació stop motion
site_author: Ariadna Landete
site_url: https://arialandete.github.io/Apunts-Stop-Motion/

theme:
  name: material
  language: ca
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate
    - content.code.copy
  palette:
    - scheme: default
      primary: deep orange
      accent: amber

extra_css:
  - css/estil.css

nav:
  - Inici: index.md
  - Apunts:
      - Què és l'stop motion?: apunts.md
      - Fases del procés: fases.md
  - Activitat: activitat.md
  - Avaluació: avaluacio.md
  - Publicació: publicacio.md

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
